config/routes.rb
Uu2::Application.routes.draw do

  get "friendmap/index"

  resources :attachables

  resources :galleries

  resources :avatars
  
  resources :authentications

  
  resources :albums do
  resources :pictures do
    collection do
      post 'make_default'
    end
  end
  end
  
  resources :pictures

resources :messages do 
  get :autocomplete_profile_firstname, :on => :collection
end

  resources :memberships, :only => [:create, :destroy]
  
  resources :groups do
    resources :albums do 
      resources :pictures
    end
    resource :scribbles
    member do
    post 'groupscribble', :action => :newgroupscribble
  end 
  end
  
  resources :localfeeds do
    resource :scribbles
    member do
      post 'localscribble', :action => :newlocalscribble
    end
  end

  resources :locations
  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
  
  resources :users do
    resource :avatar
    
  resource :profile 
  
  
  collection do
    post 'uploadfoto', :action => :uploadfoto
  end

  end  

  resources :scribbles do
        member do
      post 'localscribble', :action => :newlocalscribble
    end
    resources :comments

  end
resource :user
  get "navigation/home"
  
  
  
  root :to => 'localfeeds#index'
  get "navigation/feeds"
  get  "refresh"  => "navigation#refreshscribbles", :as => "refresh"
  get  "promote"  => "navigation#votedup", :as => "promote"
  get  "demote"  => "navigation#voteddown", :as => "demote"
  
  
  
   resources :friendships do
    collection do
      get 'request',:as=>"addfriend"
      get 'accept',:as=>"accept_fr"
      get 'reject',:as=>"reject_fr"
    end
  end
 
 get 'message/compose', to: 'messages#new', as: :compose

  
 resources :messages do
    collection do
      get 'index', to: 'messages#index', as: :index
      get 'sent', to: 'messages#sent', as: :sent
      post 'reply', to: 'messages#reply', as: :reply
      post 'trash', to: 'messages#trash', as: :trash
    end
  end

  post 'mailbox/empty_trash', to: 'mailboxes#empty_trash', as: :empty_trash
  get 'mailbox/:mailbox', to: 'mailboxes#show', as: :mailbox
  get 'mailbox/:mailbox/:id', to: 'messages#show', as: :mailbox_message
  
   match "/showusers/:id" => "users#showconnections", :as=>"showusers"
   

end

app/models/message.rb
require 'message_sender'
class Message < ActiveRecord::Base
  after_save :add_to_soulmate
  before_destroy :remove_from_soulmate
  
  
  has_ancestry
  attr_accessor :draft
  serialize :recipient_ids, Array 
  
  belongs_to :user
  
  validates :body, :user_id, presence: true
  validate :locak_down_attributes, on: :update
  
  scope :ordered,   -> {order('created_at asc')}
  scope :active,    -> { not_trashed.not_deleted}
  
  scope :draft,     -> { where('sent_at is NULL')}
  scope :not_draft, -> { where('sent_at is not NULL')}
  
  scope :sent,      -> { where('sent_at is not NULL')}
  scope :unsent,    -> { where('sent_at is NULL') }
  
  scope :received,  -> { where('received_at is not NULL')}
  scope :not_received, -> { where('received_at is NULL')}
  
  scope :trashed,   -> { where('trashed_at is not NULL')}
  scope :not_trashed, -> { where('trashed_at is NULL')}
  
  scope :deleted,   -> {where ('deleted_at is not NULL' )}
  scope :not_deleted, -> {where ('deleted_at is NULL')}
  
  scope :by_user, lambda { |user| where(user_id: user.id) }
  scope :inbox,   lambda { |user| by_user(user).active.received }
  scope :outbox,  lambda { |user| by_user(user).active.sent }
  scope :drafts,  lambda { |user| by_user(user).active.draft.not_received }
  scope :trash,   lambda { |user| by_user(user).trashed.not_deleted }

  scope :read,    lambda { |user| by_user(user).where('read_at is not NULL').received }
  scope :unread,  lambda { |user| by_user(user).where('read_at is NULL').received }

  
    
  attr_accessible :body, :read_at, :recepient_id, :sender_id, :profile_name, :profile_firstname, :recipient_ids, :draft, :user, :received_at, :editable
  attr_accessor :reply, :parent, :profile
  
  
  def active?
    !trashed? && !deleted?
  end
  
  def sender=sending_user
    user = sending_user
  end
  
  def sender
    sent? ? user : parent.user
  end
  
  def recipients
    sent? ? children.collect(&:user) : parent.recipients
  end
  
  def recipients= users
    users.each {|u| recipients_ids << u.id}
    
  end
  
  def recipient_list
    recipient_ids.reject(&:blank?).map {|id| User.find id}
  end
  
  def mailbox
    case
    when sent? then :outbox
    when received? then :inbox
    when !new_record? && unsent? then :drafts
    when trashed? then :trash
    else
      :compose
  end
  end
  
  def send!
    lock.synchronize do 
      MessageSender.new(self).run unless draft?
    end
  end
  
  def replay! options={}
    if parent
      replay = children.create!(subject: options.fetch(:subject, subject),
      body: options.fetch(:body, nil),
      user: user,
      recipients: [parent.user])
      replay.send!
    end
  end
  
  def receive!
    update(received_at: Time.zone.now)
  end
  def read!
    update(read_at: Time.zone.now) unless self.read_at.present?
  end
  
  def trash!
    update(trashed_at: Time.zone.now)
  end
  def deleted!
    update(deleted_at: Time.zone.now)
  end
  
  %W[sent received trashed deleted read].each do |act|
    define_method "#{act}?" do
      self.send(:"#{act}_at").present?
    end
    end
      
      def unread?
        !read?
      end
      
      def uneditable?
        !editable?
      end
      def unsent?
        !sent?
      end
      def draft?
        self.draft == '1'
      end
      def sent_date
        sent_at || received_at
      end
      
      private
      def lock_down_attributes
        return if editable?
        errors.add(:base, 'Cannot edit') unless deleted_at_changed? || trashed_at_changed? || read_at_changed?
      end
      def lock
        @lock ||= Mutex.new
      end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  #before_action :message, only: [:show, :update, :destroy]
  #before_action :can_view_message, only: [:show, :edit, :destroy]

  autocomplete :profile, :firstname, :update_elements => {:id => '#id'}
  
  def index
    mailbox = Mailbox.new(current_user)
    @inbox_messages = mailbox.inbox
  end

  def sent
    mailbox = Mailbox.new(current_user)
    @sent_messages = mailbox.outbox
  end

  def new
    @message = current_user.messages.new
  end

  def create
    message_params[:recipient_ids]=message_params[:recipient_ids].select{|r| !r.blank?}
    @message = Message.new(message_params.merge(:user=> current_user))
    if @message.save
      send_message
    else
      render :new
    end
  end

  def edit
    redirect_to message unless message.unsent?
  end

  def update
    message.update(message_params)
    send_message
  end

  def show
    @message = Message.find(params[:id])
    @message.read! if @message.received? || @message.unread?
  end

  def reply
    @message = Message.find(params[:id])
    if params[:message][:body]
      @message.reply! message_params.merge(:user=> current_user)
      set_flash_message :notice, :replied
      redirect_to index_messages_path
    else
      set_flash_message :alert, :invalid
      redirect_to :back
    end
  end

  def trash
    @message = Message.find(params[:id])
    @message.trash!
    set_flash_message :notice, :trashed
    redirect_to index_messages_path
  end

  def destroy
    message.delete!
    set_flash_message :notice, :deleted
    redirect_to mailbox_path(:inbox)
  end

  def empty_trash
    Mailbox.new(current_user).empty_trash!
    set_flash_message :notice, :trash_emptied
    redirect_to mailbox_path(:inbox)
  end

  private
  def message
    @message ||= Message.find(params[:id])
  end
  helper_method :message

  def message_params
    params[:message]
  end

  def send_message
    message.send!
    notice = message.sent? ? set_flash_message(:notice, :sent) : set_flash_message(:notice, :saved)
    redirect_to :back, notice: notice
  end

  def mailbox_name
    params[:mailbox] || message.mailbox.to_s
  end
  helper_method :mailbox_name

  def can_view_message
    unless mine?
      set_flash_message :notice, :unauthorised
      redirect_to mailbox_path(:inbox)
    end
  end

  def mine?
    message.user == current_user
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= render "shared/messages_menu" %>
<% if @message.errors.present? %>
  <label><%= @message.errors.full_messages %></label>
<% end %>
<%= form_for @message do |f| %>
  <fieldset>
  <%= f.label "send to"%>
  <%= f.autocomplete_field :recipient_ids, autocomplete_profile_firstname_messages_path, :id=>"#id", 'data-delimiter' => ',', :multiple => true, :update_elements => {:id => '#input#profile_id', :name => 'input#profile_id'} %>

  <%= f.label "message"%>
  <%= f.text_area :body,:required=> false, :placeholder=> 'Hi, how are you? ...',:input_html => {:rows=>5,:style=>'width:100%'} %>
  <%= f.label "draft ?"%>
  <%= f.check_box :draft, :as=>:boolean , :label=>'Save as Draft?' %>
  <%= f.submit %>
  </fieldset>
<% end %>

app/views/messages/_inbox.html.erb
<h2>Your Inbox</h2>
<% if @messages.size == 0 %>
No messages in your Inbox
<% else %>
                <%= form_tag delete_multiple_user_messages_path, :method=>:post do %>
                        <table  class="table table-bordered">
                                <tr>
                                        <th>Delete?</th>
                                        <th>Sent</th>
                                        <th>Sender</th>
                                        <th>Sent</th>
                                </tr>
                                        <% for message in @messages %>
                                                <tr>
                                                        <td><%= check_box_tag "delete[]", message.id %></td>
                                                        <td>
                                                                <% if message.read? %>
                                                                  <%= link_to h(message.body), user_message_path(@user, message) %>
                                                                <% else %>
                                                                  <%= link_to "#{h(message.body)} (unread)", user_message_path(@user, message) %>
                                                                <% end %>
                                                        </td>
                                                        <td><%= "#{message.sender.full_name}" %></td>
                                                <td><%=h message.created_at.to_s(:long) %></td>
                                                </tr>
                        <% end %>
                        </table>
                <%= submit_tag "Delete selected" %> |
                <% end %>
<%= link_to "Compose New Message", new_user_message_path(@user)%> | 
<%= link_to "View Sent Messages", user_messages_path(current_user, :mailbox => :sent)%>
<% end %>

app/views/messages/_messages_menu.html.erb
<% action_arr=
[
  ['index','index','Inbox'],
  ['sent','sent','Sent']
]%>
<ul class="nav nav-tabs">
  <% action_arr.each do |arr| %>
  <%  matching_actions,action,display_string = arr%>
  <%  class_name = (matching_actions.split(",").to_a.include?(controller.action_name.downcase)==true)? 'active' : 'plain'%>
  <li class=<%=class_name%>>
    <%= link_to "#{display_string}" , eval("#{action}_messages_path")%>
  </li>
  <% end %>
  </ul>

app/views/messages/_sent.html.erb
<h2>Sent Messages</h2>
<% if @messages.size == 0 %>
No Sent messages
<% else %>
                <%= form_tag delete_multiple_user_messages_path, :method=>:post do %>
                        <table class="table table-bordered">
                                <tr>
                                        <th>Delete?</th>
                                        <th>Subject</th>
                                        <th>Send To</th>
                                        <th>Sent At</th>
                                </tr>
                                <% for message in @messages %>
                                <tr>
                                        <td><%= check_box_tag "delete[]", message.id %></td>
                                        <td><%= link_to h(message.body), user_message_path(@user, message) %></td>
                                        <td><%= "#{message.recepient.full_name}" %></td>
                                        <td><%=h message.created_at.to_s(:long) %></td>
                                </tr>
                                <% end %>
                        </table>
                <%= submit_tag "Delete selected" %>
                <% end %>
        <%= link_to "View Inbox", user_messages_path(current_user, :mailbox=>:inbox)%>
<% end %>

app/views/messages/edit.html.haml
= render 'form'

app/views/messages/index.html.erb
<%= render "shared/messages_menu" %>
<% if @inbox_messages.blank? %>
<label>Inbox is empty</label>


<% else %>
<table class="table table-hover table-bordered">
		<thead>
			<th>Subject</th>
			<th>Sender</th>
			<th></th>
		</thead>
		<tbody>
		<% @inbox_messages.each do |message| %>
			<tr>
				<td>
					<% if message.unread? %>
						<i class="fa fa-sign-in"></i>
					<% end %>
					<%=h message.subject %>
				</td>
				<td><%=h message.parent.sender.full_name %> at <%=h message.parent.sent_at.to_date %></td>
				<td><%= link_to("Show",message_path(:id=>message)) %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
<% end %>

app/views/messages/new.html.haml
= render 'shared/messages_menu' 
= render 'form'

app/views/messages/sent.html.erb
<%= render "shared/messages_menu" %>
<% if @sent_messages.blank? %>
<label>Sent Items is empty</label>
<% else %>
	<table class="table table-hover table-bordered">
		<thead>
			<th>To</th>
			<th>On</th>
		</thead>
		<tbody>
		<% @sent_messages.each do |message| %>
			<tr>
				<td><%=h message.recipient_list.map{|user| user.message_title}.join(",") %></td>
				<td><%=h message.sent_at %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
<% end %>

app/views/messages/show.html.haml
%section#discuss(class = "#{mailbox_name}")
  %h2= mailbox_name.humanize


  .message
    %ul.headers
      %li.subject Subject: #{message.try(:subject)}
      %li.sender Sender: #{message.sender}
      %li.sent_at Date: #{message.sent_date.to_date}
      - # Do we want recipient names to be links? or have any data attributes like the user.id?
      %li.recipients Recipients: #{message.recipients.join(', ')}

    .body= markdown(message.body)

    - unless message.trashed?
      .move_to_trash
        = simple_form_for @message, url: message_trash_path(@message), method: :post do |f|
          = f.submit 'Move to trash'

    - if message.received?
      .compose.reply
        %h3 Reply
        = simple_form_for @message, url: message_reply_path(@message), method: :post do |f|
          = f.input :subject, input_html: { value: "Re: #{@message.subject}" }
          = f.input :body, required: false, label: 'Your message', input_html: { value: '' }
          = f.input :draft, as: :boolean
          = f.submit 'Reply'