config/routes.rb
Uu2::Application.routes.draw do

  get "friendmap/index"

  resources :attachables

  resources :galleries

  resources :avatars
  
  resources :authentications

  
  resources :albums do
  resources :pictures do
    collection do
      post 'make_default'
    end
  end
  end
  
  resources :pictures

resources :messages do 
  get :autocomplete_profile_firstname, :on => :collection
end

  resources :memberships, :only => [:create, :destroy]
  
  resources :groups do
    resources :albums do 
      resources :pictures
    end
    resource :scribbles
    member do
    post 'groupscribble', :action => :newgroupscribble
  end 
  end
  
  resources :localfeeds do
    resource :scribbles
    member do
      post 'localscribble', :action => :newlocalscribble
    end
  end

  resources :locations
  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
  
  resources :users do
    resource :avatar
    
  resource :profile 
  
  
  collection do
    post 'uploadfoto', :action => :uploadfoto
  end

  end  

  resources :scribbles do
        member do
      post 'localscribble', :action => :newlocalscribble
    end
    resources :comments

  end
resource :user
  get "navigation/home"
  
  
  
  root :to => 'localfeeds#index'
  get "navigation/feeds"
  get  "refresh"  => "navigation#refreshscribbles", :as => "refresh"
  get  "promote"  => "navigation#votedup", :as => "promote"
  get  "demote"  => "navigation#voteddown", :as => "demote"
  
  
  
   resources :friendships do
    collection do
      get 'request',:as=>"addfriend"
      get 'accept',:as=>"accept_fr"
      get 'reject',:as=>"reject_fr"
    end
  end
 
 get 'message/compose', to: 'messages#new', as: :compose

  
 resources :messages do
    collection do
      get 'index', to: 'messages#index', as: :index
      get 'sent', to: 'messages#sent', as: :sent
      post 'reply', to: 'messages#reply', as: :reply
      post 'trash', to: 'messages#trash', as: :trash
    end
  end

  post 'mailbox/empty_trash', to: 'mailboxes#empty_trash', as: :empty_trash
  get 'mailbox/:mailbox', to: 'mailboxes#show', as: :mailbox
  get 'mailbox/:mailbox/:id', to: 'messages#show', as: :mailbox_message
  
   match "/showusers/:id" => "users#showconnections", :as=>"showusers"
   

end

app/models/group.rb
class Group < ActiveRecord::Base
  acts_as_authorization_object
  
  attr_accessible :image_attributes, :name, :location_id, :location_name, :scribble_attributes, :group_type, :privacy, :about, :membership_id, :event_id, :headline
  
  has_many :users, :through => :memberships
  
  has_many :memberships
  
  has_one :location
  
  has_many :scribbles, :as => :scribbled
  accepts_nested_attributes_for :scribbles
  
  has_many :galleries, :as => :gallerable, :dependent => :destroy
  accepts_nested_attributes_for :galleries

  has_many :albums, :as => :albumable, :dependent => :destroy
  accepts_nested_attributes_for :albums

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :loadscribbles
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @groupscribbles = Scribble.where(:scribbled_id => @group, :scribbled_type => "Group")
    @albumable = @group
    @albums = @albumable.albums
    @album = Album.new
  end

  def new
    @group = Group.new
  end

  def create
    
    @group = Group.new(params[:group])
    if @group.save
      redirect_to @group, :notice => "Successfully created group."
    else
      render :action => 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to @group, :notice  => "Successfully updated group."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_url, :notice => "Successfully destroyed group."
  end
  
   def newgroupscribble
    @group = Group.find(params[:id])
    @user = current_user
    @newgroupscribble = @group.scribbles.create(params[:scribble])
    redirect_to @group
    #@localscribble.scribbled = @user
    #@localscribble.scribbled = @localfeed
  end
  
    def loadscribbles
    if params[:group_id]
      @group = Group.find(params[:group_id])
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_about.html.erb
<p>
  <strong>About:</strong>
  <%= @group.about %>
</p>

app/views/groups/_album.html.erb
<%= render "albums/index"%>
<%= render "albums/form" %>

app/views/groups/_feeds.html.erb
<% @scribble = Scribble.new %>

<%=render :partial => 'newgroupscribble.html.erb', :locals => {:scribble => @scribble, :group => @group}%>

<% if @groupscribbles.empty? %>
<h3> no scribbles yet </h3>
<% else %>
  <% @groupscribbles.each do |scribble| %>
    <div class="scribblebody"> 
          <div class="votebox">

                       <a href="" id="<%= scribble.id %>" name="promote" class="votes">
                       <div class='up'></div><%= scribble.promotes %> promotes</a>
         
                       <a href=""  id="<%= scribble.id %>"  name="demote" class="votes">
                       <div class='down'></div><%= scribble.demotes %> demotes</a>

          </div>
          <div class="scribbleimg"><img src="assets/default_avatar.png" style='width:50px;height:50px'/></div>
          <div class="scribbletext">
          <blockquote>
          <p><%= scribble.post %></p>
          <small><%= scribble.posted_by %></small>
          </blockquote>
          <div class="scribbletime">created at  <%= scribble.created_at %></div></div>
          <%= render :partial=>"comments/postedcomments",:locals=>{:scribble=>scribble} %>
          <%= render :partial=>"comments/new",:locals=>{:scribble=>scribble} %> 
     </div>
  <% end %>
<% end %>

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :group_type %><br />
    <%= f.text_field :group_type %>
  </p>
  <p>
    <%= f.label :privacy %><br />
    <%= f.text_field :privacy %>
  </p>
    <p>
    <%= f.label :location_name %><br />
    <%= f.text_field :location_name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/groups/_gallery_form.html.erb
<div id="new-pilot-fields" class="modal fade" data-backdrop="static">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Add a Pilot<%= " to the #{ @group.name } Pilot Roster" unless @group.name.nil? %></h3>
  </div>
  <div class="modal-body">
    <fieldset>
      <div class="control-group">
        <%= f.label(:first_name, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:first_name, :class => "input-xlarge field") %>
        </div>
      </div>
 
      <div class="control-group">
        <%= f.label(:last_name, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:last_name, :class => "input-xlarge field") %>
        </div>
      </div>
 
      <div class="control-group">
        <%= f.label(:call_sign, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:call_sign, :class => "input-xlarge field") %>
        </div>
      </div>
      <%= f.hidden_field(:_destroy, :class => "field") %>
    </fieldset>
  </div>
  <div class="modal-footer">
    <button id="addButton" type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true" title="Add this Pilot to the list of Pilots that are assigned to this Ship.">Add</button>
    <button id="cancelButton" type="button" class="btn btn-inverse" data-dismiss="modal" aria-hidden="true" title="Close this screen without adding the Pilot to the list.">Cancel</button>
  </div>
</div>
 
<script type="text/javascript">
  pilotFieldsUI.init();
</script>

app/views/groups/_newgroupscribble.html.erb

<%= form_for @scribble, :url => url_for(:controller => 'groups', :action => 'newgroupscribble') do |f| %>
<div class="">
        <div class="field">
                <%= f.text_area :post, :rows=>3,:placeholder=>"What's on your mind,#{current_user.full_name}?",
                :class=>"sribble-status-text"
                %>
                <%= f.hidden_field :posted_by, :value => current_user.full_name%>
        </div>
        <div class="sribble-status-actions" >
                <%= f.submit "Share",:class=>"btn btn-info" %>
        </div>
</div>
<% end %>

app/views/groups/edit.html.erb
<% title "Edit Group" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @group %> |
  <%= link_to "View All", groups_path %>
</p>

app/views/groups/index.html.erb
<% title "Groups" %>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Type</th>
    <th>Privacy</th>
    <th>About</th>
    <th>Membership</th>
    <th>Event</th>
    <th>Headline</th>
  </tr>
  <% for group in @groups %>
    <tr>
      <td><%= group.name %></td>
      <td><%= group.location_id %></td>
      <td><%= group.group_type %></td>
      <td><%= group.privacy %></td>
      <td><%= group.about %></td>
      <td><%= group.membership_id %></td>
      <td><%= group.event_id %></td>
      <td><%= group.headline %></td>
      <% if current_user.joined?(group)%>
      <td><%= button_to "Leave Group",{:controller => :memberships, :action => 'destroy', :id => group.id }, :method => :delete%></td>
      <% else %>
      <td><%= button_to "Join Group", memberships_path(:group_id => group.id), :method => :create%></td>
      <% end %>
      <td><%= link_to "Show", group %></td>
      <td><%= link_to "Edit", edit_group_path(group) %></td>
      <td><%= link_to "Destroy", group, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Group", new_group_path %></p>

app/views/groups/new.html.erb
<% title "New Group" %>

<%= render 'form' %>

<p><%= link_to "Back to List", groups_path %></p>

app/views/groups/show.html.erb
<script src="bootstrap.min.js"></script>
<% title "Group" %>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>
<p>
  <strong>Location:</strong>
  <%= @group.location_id %>
</p>
<p>
  <strong>Type:</strong>
  <%= @group.group_type %>
</p>
<p>
  <strong>Privacy:</strong>
  <%= @group.privacy %>
</p>
<p>
  <strong>About:</strong>
  <%= @group.about %>
</p>
<p>
  <strong>Membership:</strong>
  <%= @group.membership_id %>
</p>
<p>
  <strong>Event:</strong>
  <%= @group.event_id %>
</p>
<p>
  <strong>Headline:</strong>
  <%= @group.headline %>
</p>

<p>
  <%= link_to "Edit", edit_group_path(@group) %> |
  <%= link_to "Destroy", @group, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", groups_path %>
</p>

<a type="button" class="btn" style="width:100%;" href="#test_modal" data-toggle="modal">Add Image</a>

<ul class = "nav nav-pills">
	<li class= "active">
		<a class = "tabs" href"#section-1" section= "section-1">
			<span>feeds</span> <span class="badge badge-inverse"><%= @group.id%></span>
			</a>
			</li>
			        <li>
                <a class="tabs" href="#section-2" section="section-2">
                        <span>about</span> <span class="badge badge-inverse"><%= @group.id%></span>
                </a>
        </li> 
        
        
        
        	<li>
                <a class="tabs" href="#section-3" section="section-3">
                        <span>Events</span> <span class="badge badge-inverse"><%= @group.id%></span>
                </a>
        </li> 
        <li>
                <a class="tabs" href="#section-4"section="section-4">
                        <span>album</span> 
                </a>
        </li>
                <li>
                <a class="tabs" href="#section-5"section="section-5">
                        <span>people</span>
                </a>
        </li>
</ul> 

<div class="content" id="section-1" style="display:block;">
        <%= render :partial => "groups/feeds" %>
</div>

<div class="content" id="section-2" style="display:none;">
        <%= render :partial => "groups/about" %>
</div>

<div class="content" id="section-3" style="display:none;">
        <%= render :partial => "groups/events" %>
</div>

<div class="content" id="section-4" style="display:none;">
        <%= render :partial => "groups/album"%>
</div>
<div class="content" id="section-4" style="display:none;">
        <%= render :partial => "groups/people"%>
</div>

<script>
$(".tabs").click(function() {
  $(this).parent().parent().children().removeClass("active");
  $(this).parent().addClass("active");
  $(".content").css("display","none");
  $('#'+$(this).attr('section')).css("display","block");
});
</script>