config/routes.rb
Uu2::Application.routes.draw do

  get "friendmap/index"

  resources :attachables

  resources :galleries

  resources :avatars
  
  resources :authentications

  
  resources :albums do
  resources :pictures do
    collection do
      post 'make_default'
    end
  end
  end
  
  resources :pictures

resources :messages do 
  get :autocomplete_profile_firstname, :on => :collection
end

  resources :memberships, :only => [:create, :destroy]
  
  resources :groups do
    resources :albums do 
      resources :pictures
    end
    resource :scribbles
    member do
    post 'groupscribble', :action => :newgroupscribble
  end 
  end
  
  resources :localfeeds do
    resource :scribbles
    member do
      post 'localscribble', :action => :newlocalscribble
    end
  end

  resources :locations
  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
  
  resources :users do
    resource :avatar
    
  resource :profile 
  
  
  collection do
    post 'uploadfoto', :action => :uploadfoto
  end

  end  

  resources :scribbles do
        member do
      post 'localscribble', :action => :newlocalscribble
    end
    resources :comments

  end
resource :user
  get "navigation/home"
  
  
  
  root :to => 'localfeeds#index'
  get "navigation/feeds"
  get  "refresh"  => "navigation#refreshscribbles", :as => "refresh"
  get  "promote"  => "navigation#votedup", :as => "promote"
  get  "demote"  => "navigation#voteddown", :as => "demote"
  
  
  
   resources :friendships do
    collection do
      get 'request',:as=>"addfriend"
      get 'accept',:as=>"accept_fr"
      get 'reject',:as=>"reject_fr"
    end
  end
 
 get 'message/compose', to: 'messages#new', as: :compose

  
 resources :messages do
    collection do
      get 'index', to: 'messages#index', as: :index
      get 'sent', to: 'messages#sent', as: :sent
      post 'reply', to: 'messages#reply', as: :reply
      post 'trash', to: 'messages#trash', as: :trash
    end
  end

  post 'mailbox/empty_trash', to: 'mailboxes#empty_trash', as: :empty_trash
  get 'mailbox/:mailbox', to: 'mailboxes#show', as: :mailbox
  get 'mailbox/:mailbox/:id', to: 'messages#show', as: :mailbox_message
  
   match "/showusers/:id" => "users#showconnections", :as=>"showusers"
   

end

app/models/localfeed.rb
class Localfeed < ActiveRecord::Base
  attr_accessible :city, :scribble_id, :location_id, :localfeed_id, :scribble_attributes, :localfeed_attributes
  
  belongs_to :location
  has_many :scribbles, :as => :scribbled
  accepts_nested_attributes_for :scribbles
  validates :city, :presence => true, :uniqueness => true
  
  # after_validation :savefeed
#   
#   
#   
#   
  # def savefeed
    # self.save!
  # end
end

app/controllers/localfeeds_controller.rb
class LocalfeedsController < ApplicationController
  before_filter :loadscribbles
  def index
   
    @localfeeds = Localfeed.all
  respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @localfeeds }
    end
  end

  def show
    # @newlocalscribble = Scribble.new
    @localfeeds = Localfeed.all
    @localfeed = Localfeed.find(params[:id])
    @city = request.location.city
    # #@feed = loadscribbles
    # @feed = @localfeed.scribbles(:all, :order => 'scribbles.created_at DESC')
    # #@localfeeds = Localfeed.all
    # respond_to do |format|
      # format.html # index.html.erb
      # format.json { render :json => @feed }
    # end
    if @localfeed.nil?
      @localfeed = Localfeed.find_by_city(current_user.location.city || @city)
    else
    @localscribbles = Scribble.where(:scribbled_id => @localfeed)
    end
    
      respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @localscribbles }
    end
  end

  def new
    @localfeed = Localfeed.new
    @feed = Localfeed.find_by_id(params[:localfeed])
  end

  def create
    @localfeed = Localfeed.new(params[:localfeed])
    if @localfeed.save
      redirect_to @localfeed, :notice => "Successfully created localfeed."
    else
      render :action => 'new'
    end
    

  end

  def edit
    @localfeed = Localfeed.find(params[:id])
  end

  def update
    @localfeed = Localfeed.find(params[:id])
    if @localfeed.update_attributes(params[:localfeed])
      redirect_to @localfeed, :notice  => "Successfully updated localfeed."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @localfeed = Localfeed.find(params[:id])
    @localfeed.destroy
    redirect_to localfeeds_url, :notice => "Successfully destroyed localfeed."
  end
  
  def loadscribbles
    if params[:localfeed_id]
      @localfeed = Localfeed.find(params[:localfeed_id])
    end
  end
  
  def newlocalscribble
    @localfeed = Localfeed.find(params[:id])
    @user = current_user
    @newlocalscribble = @localfeed.scribbles.create(params[:scribble])
    redirect_to @localfeed
    #@localscribble.scribbled = @user
    #@localscribble.scribbled = @localfeed
  end
end

app/helpers/localfeeds_helper.rb
module LocalfeedsHelper
end

app/views/localfeeds/_feedlist.html.erb
<% title "feedlist" %>

<table>
  <tr>
    <th>City</th>
  </tr>
  <% @localfeeds.each do |f| %>
    <tr>
      <td><%= link_to f.city, f %></td>
    </tr>
  <% end %>
</table>

app/views/localfeeds/_feeds.html.erb
<% @localscribbles.each do |scribble|%>
<%=scribble.post%>
<%=scribble.posted_by%>
<%=scribble.created_at%>
<%end%>

app/views/localfeeds/_form.html.erb
<%= form_for @localfeed do |f| %>

  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :scribble_id %><br />
    <%= f.number_field :scribble_id %>
  </p>
  <p>
    <%= f.label :location_id %><br />
    <%= f.number_field :location_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/localfeeds/_newlocalscribble.html.erb

<%= form_for @scribble, :url => url_for(:controller => 'localfeeds', :action => 'newlocalscribble') do |f| %>
<div class="">
        <div class="field">
                <%= f.text_area :post, :rows=>3,:placeholder=>"What's on your mind,#{current_user.full_name}?",
                :class=>"sribble-status-text"
                %>
                <%= f.hidden_field :posted_by, :value => current_user.full_name%>
        </div>
        <div class="sribble-status-actions" >
                <%= f.submit "Share",:class=>"btn btn-info" %>
        </div>
</div>
<% end %>

app/views/localfeeds/edit.html.erb
<% title "Edit Localfeed" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @localfeed %> |
  <%= link_to "View All", localfeeds_path %>
</p>

app/views/localfeeds/index.html.erb
<%= render :partial => 'feedlist' %>

app/views/localfeeds/new.html.erb
<% title "New Localfeed" %>

<%= render 'form' %>

<p><%= link_to "Back to List", localfeeds_path %></p>

app/views/localfeeds/show.html.erb
<% @scribble = Scribble.new %>



<%=render :partial => 'newlocalscribble.html.erb', :locals => {:scribble => @scribble, :localfeed => @localfeed}%>

<% if @localscribbles.empty? %>
<h3> no scribbles yet </h3>
<% else %>
  <% @localscribbles.each do |scribble| %>
    <div class="scribblebody"> 
          <div class="votebox">

                       <a href="" id="<%= scribble.id %>" name="promote" class="votes">
                       <div class='up'></div><%= scribble.promotes %> promotes</a>
         
                       <a href=""  id="<%= scribble.id %>"  name="demote" class="votes">
                       <div class='down'></div><%= scribble.demotes %> demotes</a>

          </div>
          <div class="scribbleimg"><img src="assets/default_avatar.png" style='width:50px;height:50px'/></div>
          <div class="scribbletext">
          <blockquote>
          <p><%= scribble.post %></p>
          <small><%= scribble.posted_by %></small>
          </blockquote>
          <div class="scribbletime">created at  <%= scribble.created_at %></div></div>
          <%= render :partial=>"comments/postedcomments",:locals=>{:scribble=>scribble} %>
          <%= render :partial=>"comments/new",:locals=>{:scribble=>scribble} %> 
     </div>
  <% end %>
<% end %>