config/routes.rb
Uu2::Application.routes.draw do

  get "friendmap/index"

  resources :attachables

  resources :galleries

  resources :avatars
  
  resources :authentications

  
  resources :albums do
  resources :pictures do
    collection do
      post 'make_default'
    end
  end
  end
  
  resources :pictures

resources :messages do 
  get :autocomplete_profile_firstname, :on => :collection
end

  resources :memberships, :only => [:create, :destroy]
  
  resources :groups do
    resources :albums do 
      resources :pictures
    end
    resource :scribbles
    member do
    post 'groupscribble', :action => :newgroupscribble
  end 
  end
  
  resources :localfeeds do
    resource :scribbles
    member do
      post 'localscribble', :action => :newlocalscribble
    end
  end

  resources :locations
  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
  
  resources :users do
    resource :avatar
    
  resource :profile 
  
  
  collection do
    post 'uploadfoto', :action => :uploadfoto
  end

  end  

  resources :scribbles do
        member do
      post 'localscribble', :action => :newlocalscribble
    end
    resources :comments

  end
resource :user
  get "navigation/home"
  
  
  
  root :to => 'localfeeds#index'
  get "navigation/feeds"
  get  "refresh"  => "navigation#refreshscribbles", :as => "refresh"
  get  "promote"  => "navigation#votedup", :as => "promote"
  get  "demote"  => "navigation#voteddown", :as => "demote"
  
  
  
   resources :friendships do
    collection do
      get 'request',:as=>"addfriend"
      get 'accept',:as=>"accept_fr"
      get 'reject',:as=>"reject_fr"
    end
  end
 
 get 'message/compose', to: 'messages#new', as: :compose

  
 resources :messages do
    collection do
      get 'index', to: 'messages#index', as: :index
      get 'sent', to: 'messages#sent', as: :sent
      post 'reply', to: 'messages#reply', as: :reply
      post 'trash', to: 'messages#trash', as: :trash
    end
  end

  post 'mailbox/empty_trash', to: 'mailboxes#empty_trash', as: :empty_trash
  get 'mailbox/:mailbox', to: 'mailboxes#show', as: :mailbox
  get 'mailbox/:mailbox/:id', to: 'messages#show', as: :mailbox_message
  
   match "/showusers/:id" => "users#showconnections", :as=>"showusers"
   

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :description, :album_id, :image, :crop_x, :crop_y, :crop_w, :crop_h, :gallery_token
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  belongs_to :album
  mount_uploader :image, ImageUploader
  before_create :default_name
  
  after_update :crop_image
  
  
    def default_name
    self.name ||= File.basename(image.filename, '.*').titleize if image
  end
  
  def to_jq_upload
    {
      "name" => read_attribute(:image),
      "size" => image.size,
      "url" => image.url,
      "thumbnail_url" => image.thumb.url,
      "delete_url" => id,
      "picture_id" => id,
      "delete_type" => "DELETE"
    }
  end
  
  def crop_image
    image.recreate_versions! if crop_x.present?
    current_version = self.image.current_path
    large_version = "#{Rails.root}/public" + self.image.versions[:large].to_s

    FileUtils.rm(current_version)
    FileUtils.cp(large_version, current_version)
  end
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    
    @album = Album.find(params[:album_id])
    @pictures = Picture.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
    
  end

  def show
    @picture = Picture.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  def new
    @album = Album.find(params[:gallery_id])
    @picture = @album.pictures.build
    #@picture = Picture.new(:album_id => params[:album_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  def create
    #@picture = Picture.create(params[:picture])
    p_attr = params[:picture]
    p_attr[:image] = params[:picture][:image].first if params[:picture][:image].class == Array

    if params[:album_id]
      @album = Album.find(params[:album_id])
      @picture = @album.pictures.build(p_attr)
    else
      @picture = Picture.new(p_attr)
    end

    if @picture.save
      respond_to do |format|
        format.html {
          render :json => [@picture.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => [@picture.to_jq_upload].to_json
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end
    
  end

  def edit
    @album = Album.find(params[:gallery_id])

    @picture = @album.pictures.find(params[:id])
    # @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update_attributes(params[:picture])
      redirect_to @picture, :notice  => "Successfully updated picture."
    else
      render :action => 'edit'
    end
  end

  def destroy
    
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.find(params[:id])
    #@picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_url, :notice => "Successfully destroyed picture."
  end
  
  def make_default
    @picture = Picture.find(params[:id])
    @album = Album.find(params[:album_id])

    @album.cover = @picture.id
    @album.save

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for [@album, @picture], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  
    <%= image_tag @picture.image.large.url, :id => 'cropbox' %>
  
  <% %w[x y w h].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary  btn-mini' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                album_path(@album), :class => 'btn btn-mini' %>
    <%= link_to 'Default', '', :class => 'btn btn-mini btn-success' , :id => 'make_default'%>

  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
    $(function () {
      $('#make_default').click(function(event) {
        event.preventDefault();
        $.ajax({
          url: '<%= make_default_album_pictures_path %>',
          type: 'POST',
          data: {id : <%= @picture.id %>, album_id : <%= @album.id %>}
        });
      });
    });
</script>

app/views/pictures/create.js.erb
<% if @picture.new_record? %>
  alert("Failed to upload picture: <%= j @picture.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#pictures").append("<%= j render(@picture) %>");
<% end %>

app/views/pictures/edit.html.erb
<div class="page-header">
  <h1>Edit Picture</h1>
</div>
<%= render :partial => 'form' %>

app/views/pictures/index.html.erb
<%- model_class = Picture.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:album_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= link_to picture.id, picture_path(picture) %></td>
        <td><%= picture.description %></td>
        <td><%= picture.image %></td>
        <td><%= picture.album_id %></td>
        <td><%=l picture.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_picture_path(picture), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      picture_path(picture),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_picture_path,
            :class => 'btn btn-primary' %>

app/views/pictures/make_default.js.erb
$('<span style="color: #46a546; margin-left: 15px; font-weight: bold;">Done!</span>').insertAfter('#make_default').delay(3000).fadeOut('slow');

app/views/pictures/new.html.erb
<%- model_class = @picture.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pictures/show.html.erb
<%- model_class = @picture.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @picture.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @picture.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:album_id) %>:</strong></dt>
  <dd><%= @picture.album_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pictures_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_picture_path(@picture), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              picture_path(@picture),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>